import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent { label 'master' }
  environment {
    appName = "variable" 
  }
  stages {

 stage("paso 1"){
     
      steps {
          script {			
           bat 'hola mundo'
        }
      }
    }
  }
  post {
      always {          
          deleteDir()
           bat 'fase always'
      }
      success {
            bat 'fase success'
        }

      failure {
            bat 'fase failure'
      }
      
  }
}  